### ISSUE TITLE
Spectral overrides do not work

### ISSUE THREAD

**Issue by bolmstedt** [SchwarzIT/spectral-intellij-plugin#123]
We have a multiple OpenAPI schemas where some might not follow all rules yet, and have switched off certain rules for certain schemas using overrides in our `.spectral.yml` configuration, like so:
```yml
---
extends:
  - some_ruleset.yml
overrides:
  - files:
      - "some/path/openapi.yaml"
    rules:
      some-rule: "off"
```
This is does however not work with this plugin, since it takes the content of the file to lint and creates a temporary file that it passes to Spectral.

Is there some smart way of fixing this, or could we perhaps add an option to disable the usage of a temporary file?
